package gcdiff

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseCensusKeepsCorpusRowsAndCountsTheRest(t *testing.T) {
	const text = `# a comment
testdata/hello.go:11:9	main.main	runtime.newobject	string	heap
testdata/gc_struct.go:25:10	main.Test	runtime.newobject	main_record	frame
stdlib/src/sync/cond.go:49:9	sync.NewCond	runtime.newobject	sync_Cond	heap
?	main.main	runtime.newobject	int	heap
?	sync.NewCond	runtime.newobject	sync_Cond	heap
`
	rows, drops, err := ParseCensus(text, "testdata")
	require.NoError(t, err)

	require.Len(t, rows, 2)
	assert.Equal(t, CensusRow{
		File: "hello.go", Line: 11, Col: 9,
		Func: "main.main", Allocator: "runtime.newobject", Type: "string", Placement: Heap,
	}, rows[0])
	assert.Equal(t, Frame, rows[1].Placement)

	assert.Equal(t, 1, drops.OtherTree)
	assert.Equal(t, 2, drops.NoPosition)
	// The positionless row in main.main is the one that can explain away a
	// permissive finding; the one in sync.NewCond cannot.
	assert.Equal(t, 1, drops.NoPositionInProgram)
	assert.Equal(t, 1, drops.NoPositionHeapInProgram)
}

func TestParseCensusRejectsAMalformedLine(t *testing.T) {
	_, _, err := ParseCensus("testdata/x.go:1:1\tmain.main\truntime.newobject\n", "testdata")
	assert.ErrorContains(t, err, "want 5 tab-separated fields")

	_, _, err = ParseCensus("testdata/x.go:1:1\tmain.main\truntime.newobject\tint\tregister\n", "testdata")
	assert.ErrorContains(t, err, "unknown placement")
}

// TestParseGCFlagMReadsTheDecisionsAndNothingElse pins the -m grammar this
// harness was built against. Every message shape here was taken from a real
// go1.26.1 run over the corpus; if a future release renames one, this test is
// where it should be noticed rather than in a silently shrinking matrix.
func TestParseGCFlagMReadsTheDecisionsAndNothingElse(t *testing.T) {
	const output = `# command-line-arguments
./gc_struct.go:14:6: can inline allocateGarbage
./gc_struct.go:31:17: inlining call to allocateGarbage
./gc_struct.go:16:13: &record{...} escapes to heap
./gc_struct.go:25:13: new(record) does not escape
./gc_struct.go:31:17: &record{...} escapes to heap
./gc_struct.go:5:6: moved to heap: index
./gc_struct.go:6:11: make(map[int]int, 4) does not escape
./gc_struct.go:7:11: make([]int, 4) escapes to heap
./gc_struct.go:8:11: map[string]int{...} does not escape
./gc_struct.go:9:14: ... argument does not escape
./gc_struct.go:3:10: leaking param: c
./gc_struct.go:12:2: main ignoring self-assignment in b.buf = b.buf[:0]
./gc_struct.go:13:2: devirtualizing hash.Write to *fnv.sum64a
./gc_struct.go:15:2: index bounds check elided
./gc_struct.go:17:2: zero-copy string->[]byte conversion
<autogenerated>:1: "called entry on non-entry node" escapes to heap
/usr/lib/go/src/sort/sort.go:100:21: x escapes to heap
`
	report, err := ParseGCFlagM("gc_struct.go", output)
	require.NoError(t, err)
	assert.Empty(t, report.Unknown)
	assert.Equal(t, 1, report.InlineCalls)
	// The <autogenerated> line and the GOROOT line are both positions outside
	// the program.
	assert.Equal(t, 2, report.Foreign)

	type decision struct {
		line      int
		subject   string
		placement Placement
		kind      Kind
		inlined   bool
	}
	got := make([]decision, 0, len(report.Decisions))
	for _, entry := range report.Decisions {
		got = append(got, decision{entry.Line, entry.Subject, entry.Placement, entry.Kind, entry.Inlined})
	}
	assert.Equal(t, []decision{
		{16, "&record{...}", Heap, KindObject, false},
		{25, "new(record)", Frame, KindObject, false},
		// The copy inlined into line 31: the same allocation as line 16's,
		// which gc attributes to the call site and goc attributes to line 16.
		{31, "&record{...}", Heap, KindObject, true},
		{5, "index", Heap, KindObject, false},
		{6, "make(map[int]int, 4)", Frame, KindMap, false},
		{7, "make([]int, 4)", Heap, KindSlice, false},
		{8, "map[string]int{...}", Frame, KindMap, false},
		{9, "... argument", Frame, KindSlice, false},
	}, got)
}

func TestParseGCFlagMReportsAMessageItDoesNotKnow(t *testing.T) {
	report, err := ParseGCFlagM("x.go", "./x.go:1:2: teleported to the heap\n")
	require.NoError(t, err)
	assert.Equal(t, []string{"./x.go:1:2: teleported to the heap"}, report.Unknown)
	assert.Empty(t, report.Decisions)
}

func TestSubjectKindClassifiesByConstruct(t *testing.T) {
	for subject, want := range map[string]Kind{
		"make(chan int, 1)":         KindChan,
		"make(chan<- string)":       KindChan,
		"make(map[int]int)":         KindMap,
		"map[string][]byte{...}":    KindMap,
		"make([]byte, 16)":          KindSlice,
		"[]string{...}":             KindSlice,
		"... argument":              KindSlice,
		"&record{...}":              KindObject,
		"new(record)":               KindObject,
		`"a literal"`:               KindObject,
		"func literal":              KindObject,
		"index":                     KindObject,
		"([]byte)(\"abc\")":         KindObject,
		"x + y":                     KindObject,
		"append":                    KindObject,
		"context.backgroundCtx{}":   KindObject,
		"http.Header{...}":          KindObject,
		"chanOfThings{...}":         KindObject,
		"makeSomething(1)":          KindObject,
		"maplike{...}":              KindObject,
		"[]byte(s)":                 KindSlice,
		"make(map[int]struct{}, 8)": KindMap,
	} {
		assert.Equal(t, want, subjectKind(subject), "subject %q", subject)
	}
}

// TestJoinFoldsALineAndKeepsTheDenominatorHonest is the whole join in
// miniature: a program that builds, a program that does not, a line each
// compiler decides alone, and a line carrying two allocations.
func TestJoinFoldsALineAndKeepsTheDenominatorHonest(t *testing.T) {
	census := []CensusRow{
		{File: "a.go", Line: 10, Col: 2, Func: "main.main", Allocator: "runtime.newobject", Type: "int", Placement: Frame},
		{File: "a.go", Line: 20, Col: 2, Func: "main.main", Allocator: "runtime.newobject", Type: "int", Placement: Heap},
		{File: "a.go", Line: 30, Col: 2, Func: "main.main", Allocator: "runtime.newobject", Type: "int", Placement: Frame},
		{File: "a.go", Line: 30, Col: 9, Func: "main.main", Allocator: "runtime.newobject", Type: "int", Placement: Heap},
		{File: "a.go", Line: 40, Col: 2, Func: "main.main", Allocator: "runtime.makechan", Type: "chan_int", Placement: Heap},
		{File: "b.go", Line: 5, Col: 2, Func: "main.main", Allocator: "runtime.newobject", Type: "int", Placement: Heap},
	}
	programs := []Program{
		{
			Name: "a.go",
			Report: &GCReport{Program: "a.go", Decisions: []GCDecision{
				{File: "a.go", Line: 10, Col: 6, Subject: "x", Placement: Heap, Kind: KindObject},
				{File: "a.go", Line: 20, Col: 6, Subject: "new(int)", Placement: Frame, Kind: KindObject},
				{File: "a.go", Line: 30, Col: 6, Subject: "y", Placement: Heap, Kind: KindObject},
				{File: "a.go", Line: 50, Col: 6, Subject: "z", Placement: Heap, Kind: KindObject},
				{File: "a.go", Line: 60, Col: 6, Subject: "w", Placement: Heap, Kind: KindObject, Inlined: true},
			}},
		},
		{Name: "b.go", BuildError: "use of internal package not allowed"},
	}

	result := Join(census, CensusDrops{NoPosition: 3}, programs, Options{})

	assert.Equal(t, 2, result.Coverage.Programs)
	assert.Equal(t, 1, result.Coverage.Compared)
	assert.Equal(t, 5, result.Coverage.CensusRows)
	assert.Equal(t, 1, result.Coverage.ExcludedCensusRows)
	require.Len(t, result.Coverage.Failures, 1)
	assert.Equal(t, "b.go", result.Coverage.Failures[0].Program)
	assert.Equal(t, 1, result.Coverage.Failures[0].CensusRows)
	assert.Equal(t, 1, result.Coverage.InlinedGCDecisions)
	// Line 40 is a channel gc says nothing about, so the rule supplies it.
	assert.Equal(t, 1, result.Coverage.SynthesizedChannelDecisions)

	cells := make(map[string][2]Verdict)
	for _, line := range result.Lines {
		cells[line.Key()] = line.Cell()
	}
	assert.Equal(t, map[string][2]Verdict{
		"a.go:10": {VerdictFrame, VerdictHeap}, // permissive
		"a.go:20": {VerdictHeap, VerdictFrame}, // pessimistic
		"a.go:30": {VerdictMixed, VerdictHeap}, // permissive, and ambiguous
		"a.go:40": {VerdictHeap, VerdictHeap},  // agreement, via the chan rule
		"a.go:50": {Absent, VerdictHeap},       // permissive, with no goc record
	}, cells)
	// Line 60's only decision was an inlined copy, so the line does not exist.
	assert.NotContains(t, cells, "a.go:60")

	permissive := make([]string, 0, 3)
	for _, line := range result.Permissive() {
		permissive = append(permissive, line.Key())
	}
	assert.Equal(t, []string{"a.go:10", "a.go:30", "a.go:50"}, permissive)

	pessimistic := make([]string, 0, 1)
	for _, line := range result.Pessimistic() {
		pessimistic = append(pessimistic, line.Key())
	}
	assert.Equal(t, []string{"a.go:20"}, pessimistic)
}

func TestJoinCanKeepInlinedDecisionsForTriage(t *testing.T) {
	programs := []Program{{
		Name: "a.go",
		Report: &GCReport{Program: "a.go", Decisions: []GCDecision{
			{File: "a.go", Line: 60, Col: 6, Subject: "w", Placement: Heap, Kind: KindObject, Inlined: true},
		}},
	}}
	result := Join(nil, CensusDrops{}, programs, Options{KeepInlinedGCDecisions: true})
	require.Len(t, result.Lines, 1)
	assert.Equal(t, [2]Verdict{Absent, VerdictHeap}, result.Lines[0].Cell())
}
