//go:build linux

package bpf

import (
	"encoding/binary"
	"runtime"
	"syscall"
	"testing"
	"unsafe"

	"github.com/stretchr/testify/require"
)

// sysBPF is the bpf(2) syscall number for the architectures we run tests on.
var sysBPF = map[string]uintptr{"amd64": 321, "arm64": 280, "386": 357, "arm": 386}

// loadProg asks the kernel to load and verify an eBPF program, returning the
// verifier log. A negative fd means it was rejected; errno EPERM means the
// caller lacks the privilege to load at all (the test then skips).
func loadProg(progType uint32, code []byte) (fd int, log string, errno syscall.Errno) {
	nr, ok := sysBPF[runtime.GOARCH]
	if !ok {
		return -1, "", syscall.ENOSYS
	}
	license := append([]byte("GPL"), 0)
	logBuf := make([]byte, 1<<16)
	attr := make([]byte, 120)
	binary.LittleEndian.PutUint32(attr[0:], progType)
	binary.LittleEndian.PutUint32(attr[4:], uint32(len(code)/8))
	binary.LittleEndian.PutUint64(attr[8:], uint64(uintptr(unsafe.Pointer(&code[0]))))
	binary.LittleEndian.PutUint64(attr[16:], uint64(uintptr(unsafe.Pointer(&license[0]))))
	binary.LittleEndian.PutUint32(attr[24:], 1) // log_level
	binary.LittleEndian.PutUint32(attr[28:], uint32(len(logBuf)))
	binary.LittleEndian.PutUint64(attr[32:], uint64(uintptr(unsafe.Pointer(&logBuf[0]))))
	r, _, e := syscall.Syscall(nr, 5 /* BPF_PROG_LOAD */, uintptr(unsafe.Pointer(&attr[0])), uintptr(len(attr)))
	log = string(logBuf[:clen(logBuf)])
	runtime.KeepAlive(attr)
	if e != 0 {
		return -1, log, e
	}
	return int(r), log, 0
}

func clen(b []byte) int {
	for i, c := range b {
		if c == 0 {
			return i
		}
	}
	return len(b)
}

// TestKernelVerifier compiles small C programs to eBPF and loads them, letting
// the in-kernel verifier judge the generated bytecode. It skips when the syscall
// is unavailable or the caller lacks load privileges (run as root, or with
// CAP_BPF, to exercise it).
func TestKernelVerifier(t *testing.T) {
	const (
		typeSocketFilter = 1
		typeKprobe       = 2
	)
	cases := []struct {
		name, src string
		progType  uint32
	}{
		{"arith", `int f(void*ctx){ int a=7,b=3; return a*b + (a>b?a:b); }`, typeSocketFilter},
		{"loop", `int f(void*ctx){ int r=1; for(int i=2;i<=6;i++) r*=i; return r; }`, typeSocketFilter},
		{"bitops", `unsigned f(void*ctx){ unsigned x=0xdeadbeef; return (x>>16)^(x<<4)&0xff00; }`, typeSocketFilter},
		{"helper", `unsigned long bpf_ktime_get_ns(void);
		            int f(void*ctx){ return bpf_ktime_get_ns() % 1000; }`, typeKprobe},
		{"pid", `unsigned long bpf_get_current_pid_tgid(void);
		         int f(void*ctx){ unsigned long p=bpf_get_current_pid_tgid()>>32; return p>1000?1:0; }`, typeKprobe},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			f := compileC(t, c.src)
			p, err := Compile(f)
			require.NoError(t, err)
			fd, log, errno := loadProg(c.progType, p.Bytes())
			switch {
			case errno == syscall.EPERM || errno == syscall.EACCES:
				t.Skip("no privilege to load eBPF programs (run as root or with CAP_BPF)")
			case errno == syscall.ENOSYS:
				t.Skip("bpf() syscall not available on this platform")
			case fd < 0:
				t.Fatalf("verifier rejected the program:\n%s", log)
			default:
				syscall.Close(fd)
			}
		})
	}
}
